asociaciones_3cand = """SELECT *
FROM (
    SELECT *
        FROM PREP.C_ASOCIACIONES WHERE TIPO_ASOCIACION = 1
    union
    SELECT *
        FROM PREP.C_ASOCIACIONES WHERE TIPO_ASOCIACION = 4 AND NOMBRE_ASOCIACION != 'CI'
    UNION
    SELECT *
        FROM PREP.C_ASOCIACIONES WHERE TIPO_ASOCIACION NOT IN (1,4)
) CANDIDATURAS
WHERE CANDIDATURAS.ID_ASOCIACION IN (
    SELECT DISTINCT ID_ASOCIACION
        FROM PREP.C_ESCENARIOS WHERE ID_TIPO_CANDIDATURA IN
        (%s,%s,%s)
    )
;"""

asociaciones_2cand = """SELECT *
FROM (
    SELECT *
        FROM PREP.C_ASOCIACIONES WHERE TIPO_ASOCIACION = 1
    union
    SELECT *
        FROM PREP.C_ASOCIACIONES WHERE TIPO_ASOCIACION = 4 AND NOMBRE_ASOCIACION != 'CI'
    UNION
    SELECT *
        FROM PREP.C_ASOCIACIONES WHERE TIPO_ASOCIACION NOT IN (1,4)
) CANDIDATURAS
WHERE CANDIDATURAS.ID_ASOCIACION IN (
    SELECT DISTINCT ID_ASOCIACION
        FROM PREP.C_ESCENARIOS WHERE ID_TIPO_CANDIDATURA IN
        (%s,%s)
    )
;"""

esperadas_3cand = """SELECT COUNT(ID_ACTA)
    FROM PREP.TR_ACTAS WHERE ID_TIPO_CANDIDATURA IN (%s, %s, %s)
;"""

esperadas_2cand = """SELECT COUNT(ID_ACTA)
    FROM PREP.TR_ACTAS WHERE ID_TIPO_CANDIDATURA IN (%s, %s)
;"""

fuera_cat_3cand = """SELECT COUNT(ID_ACTA_FUERA_CATALOGO)
    FROM PREP.TR_ACTAS_FUERA_CATALOGO
    WHERE ID_TIPO_CANDIDATURA IN (%s, %s, %s)
;"""

fuera_cat_2and = """SELECT COUNT(ID_ACTA_FUERA_CATALOGO)
    FROM PREP.TR_ACTAS_FUERA_CATALOGO
    WHERE ID_TIPO_CANDIDATURA IN (%s, %s)
;"""

candidaturas_3cand = """
    SELECT
    ES.ID_ESTADO as ESTADO,
    DF.ID_DISTRITO_FEDERAL as DISTRITO,
    ASOC.NOMBRE_ASOCIACION as PARTIDO_CI,
    CAND.NOMBRE_PROPIETARIO as CANDIDATURA_PROPIETARIA,
    CAND.NOMBRE_SUPLENTE as CANDIDATURA_SUPLENTE
    FROM PREP.C_DISTRITOS_FEDERALES DF
    inner join PREP.C_ESTADOS ES on DF.ID_ESTADO = ES.ID_ESTADO
    inner join PREP.C_ESCENARIOS ESC on ESC.ID_DISTRITO = DF.ID_DISTRITO_FEDERAL
    and DF.ID_ESTADO = ESC.ID_ESTADO
    inner join PREP.C_CANDIDATOS CAND on ESC.ID_ESCENARIO = CAND.ID_ESCENARIO
    inner join PREP.C_ASOCIACIONES ASOC on ESC.ID_ASOCIACION = ASOC.ID_ASOCIACION
    where ESC.ID_ASOCIACION not in (61,62,63,64,65,66,67)
    and ESC.ID_TIPO_CANDIDATURA IN (%s, %s, %s)
;"""

candidaturas_2cand = """
    SELECT
    ES.ID_ESTADO as ESTADO,
    DF.ID_DISTRITO_FEDERAL as DISTRITO,
    ASOC.NOMBRE_ASOCIACION as PARTIDO_CI,
    CAND.NOMBRE_PROPIETARIO as CANDIDATURA_PROPIETARIA,
    CAND.NOMBRE_SUPLENTE as CANDIDATURA_SUPLENTE
    FROM PREP.C_DISTRITOS_FEDERALES DF
    inner join PREP.C_ESTADOS ES on DF.ID_ESTADO = ES.ID_ESTADO
    inner join PREP.C_ESCENARIOS ESC on ESC.ID_DISTRITO = DF.ID_DISTRITO_FEDERAL
    and DF.ID_ESTADO = ESC.ID_ESTADO
    inner join PREP.C_CANDIDATOS CAND on ESC.ID_ESCENARIO = CAND.ID_ESCENARIO
    inner join PREP.C_ASOCIACIONES ASOC on ESC.ID_ASOCIACION = ASOC.ID_ASOCIACION
    where ESC.ID_ASOCIACION not in (61,62,63,64,65,66,67)
    and ESC.ID_TIPO_CANDIDATURA IN (%s, %s)
;"""

edo_dto_3cand = """SELECT DISTINCT ID_ESTADO, ID_DISTRITO
    FROM PREP.C_ESCENARIOS
    WHERE ID_PROCESO_ELECTORAL = 1 AND
    ID_TIPO_CANDIDATURA IN (%s, %s, %s)
;"""

edo_dto_2cand = """SELECT DISTINCT ID_ESTADO, ID_DISTRITO
    FROM PREP.C_ESCENARIOS
    WHERE ID_PROCESO_ELECTORAL = 1 AND
    ID_TIPO_CANDIDATURA IN (%s, %s)
;"""

info_fuera_cat = """SELECT
TAFC.ID_ACTA_FUERA_CATALOGO AS ID_ACTA,
TAFC.ID_ESTADO,
CE.NOMBRE_ESTADO AS ESTADO,
TAFC.ID_DISTRITO,
CDF.CABECERA_DISTRITAL_FEDERAL AS DISTRITO_FEDERAL,
TAFC.SECCION,
TAFC.ID_CASILLA,
TAFC.TIPO_CASILLA,
TAFC.EXT_CONTIGUA,
'3' as UBICACION_CASILLA,
TAFC.TIPO_DIGITALIZACION,
TAFC.ID_TIPO_CANDIDATURA,
'Fuera de Catálogo' AS OBSERVACIONES,
'-' AS LISTA_NOMINAL_CASILLA,
'-' AS PUBLICACION,
'2' AS CONTABILIZA,
'-' AS CLAVE_CASILLA,
'-' AS CLAVE_ACTA,
'-' AS SHA,
'-' AS FECHA_HORA_ACOPIO,
'-' AS FECHA_HORA_CAPTURA,
'-' AS FECHA_HORA_VERIFICACION,
CONCAT(TAFC.ID_TIPO_CANDIDATURA, TAFC.ID_ESTADO, TAFC.ID_DISTRITO) AS estado_distrito,
IFNULL(CDR.NOMBRE, '-') AS TIPO_DOCUMENTO,
TAFC.ID_PROCESO_ELECTORAL
FROM PREP.TR_ACTAS_FUERA_CATALOGO AS TAFC
JOIN PREP.C_ESTADOS CE ON TAFC.ID_ESTADO = CE.ID_ESTADO
JOIN PREP.C_DISTRITOS_FEDERALES CDF ON TAFC.ID_ESTADO = CDF.ID_ESTADO AND TAFC.ID_DISTRITO = CDF.ID_DISTRITO_FEDERAL
LEFT JOIN PREP.C_DOCUMENTOS_RECIBIDOS CDR ON TAFC.ID_DOCUMENTO_RECIBIDO = CDR.ID_DOCUMENTO_RECIBIDO
                AND TAFC.ID_PROCESO_ELECTORAL = CDR.ID_PROCESO_ELECTORAL
;"""

info_voto_extranjero = """SELECT
TAFC.ID_ACTA AS ID_ACTA,
CONCAT(TAFC.ID_ESTADO,TAFC.ID_DISTRITO,TAFC.ID_MUNICIPIO,TAFC.SECCION,TAFC.ID_CASILLA,TAFC.TIPO_CASILLA,TAFC.EXT_CONTIGUA,TAFC.ID_TIPO_CANDIDATURA,TAFC.CASILLA) AS CLAVE_ACTA,
CONCAT(TAFC.ID_TIPO_CANDIDATURA,TAFC.ID_ESTADO,TAFC.ID_DISTRITO) AS CLAVE_CASILLA,
TAFC.ID_ESTADO,
CE.NOMBRE_ESTADO AS ESTADO,
TAFC.ID_DISTRITO,
CDF.CABECERA_DISTRITAL_FEDERAL AS DISTRITO_FEDERAL,
TAFC.SECCION,
TAFC.ID_CASILLA,
TAFC.TIPO_CASILLA,
TAFC.EXT_CONTIGUA,
'-' as UBICACION_CASILLA,
TAFC.TIPO_DIGITALIZACION,
TAFC.ID_TIPO_CANDIDATURA,
'-' AS OBSERVACIONES,
'-' AS LISTA_NOMINAL_CASILLA,
'-' AS PUBLICACION,
'-' AS CONTABILIZA,
'-' AS CLAVE_CASILLA,
'-' AS CLAVE_ACTA,
'-' AS SHA,
'-' AS FECHA_HORA_ACOPIO,
'-' AS FECHA_HORA_CAPTURA,
'-' AS FECHA_HORA_VERIFICACION,
CONCAT(TAFC.ID_TIPO_CANDIDATURA, TAFC.ID_ESTADO, TAFC.ID_DISTRITO) AS estado_distrito,
IFNULL(CDR.NOMBRE, '-') AS TIPO_DOCUMENTO,
TAFC.ID_PROCESO_ELECTORAL
FROM PREP.TR_ACTAS AS TAFC
INNER JOIN PREP.C_ESTADOS CE ON TAFC.ID_ESTADO = CE.ID_ESTADO
INNER JOIN PREP.C_DISTRITOS_FEDERALES CDF ON TAFC.ID_ESTADO = CDF.ID_ESTADO AND TAFC.ID_DISTRITO = CDF.ID_DISTRITO_FEDERAL
INNER JOIN PREP.C_DOCUMENTOS_RECIBIDOS CDR ON TAFC.ID_DOCUMENTO_RECIBIDO = CDR.ID_DOCUMENTO_RECIBIDO
                AND TAFC.ID_PROCESO_ELECTORAL = CDR.ID_PROCESO_ELECTORAL AND TAFC.ID_DISTRITO = 0 AND TAFC.ID_ACTA = 1743;"""
